### ISSUE TITLE
How to get it running

### ISSUE THREAD

**Issue by christopherhastings** [jonluca/resy-api#2]
Wondering what I need to have installed to get going. 

Beginner here, in Python, so TypeScript is new. 

I've set up cron jobs on a Linux server, but trying to identify what needs to be done to get your code working. 

Set environmental variables, sure. 
https://linuxize.com/post/how-to-set-and-list-environment-variables-in-linux/

Can you help?

**Comment by jonluca** [comment]
Once you have the environment variables you can just run `yarn monitor`

So make sure you have node and yarn installed, then run `yarn install`, then

```TO_NUMBER="" TWILIO_AUTH="" TWILIO_NUMBER="" TWILIO_SID="" yarn monitor``` in your command line
