### ISSUE TITLE
AxiosError

### ISSUE THREAD

**Issue by gzheng92** [jonluca/resy-api#4]
I set the ENV variables, ran `yarn install`, then ran `yarn monitor` and got the following output:

```
yarn run v1.22.19
warning package.json: No license field
$ node --experimental-specifier-resolution=node --loader ts-node/esm ./src/monitor.ts
(node:32367) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32367) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 419".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
error Command failed with exit code 1.
```

On a Mac, if that matters. Any advice?

**Comment by jonluca** [comment]
Did you forget to set the environment variables for your email and password?

I pushed an update that should make the logging around the error a bit more clear.

**Comment by gzheng92** [comment]
Where does it expect the environmental variables to be set? I tried putting it in:
 - a dotenv file
 - my bash profile
 both still raise the warning

**Comment by jonluca** [comment]
You can try 
```
RESY_EMAIL="email@gmail.com" RESY_PASSWORD="password" yarn monitor
```

Although setting them in your bash profile should work if they're exported properly.

**Comment by gzheng92** [comment]
Yes, in-lining it worked.  I'm not sure why using `export BLAH="blah"` syntax in my bash profile didn't work

**Comment by jonluca** [comment]
You have to `source` the file bash profile for new changes to be reflected. Like

`source ~/.bash_profile` after editing it. Or opening up a new login shell I suppose. 

Glad its working
